package-name: TSR.Dissolve
visual-name: TSR Dissolve
destination-folder: Assets/VRLabs/Toony Standard Rebuild Modules/TSR Dissolve
extra-generated-meta:
  - path: Assets/VRLabs
    guid: 652a1ba5b00554143bc9a76307dbc4e8
  - path: Assets/VRLabs/Toony Standard Rebuild Modules
    guid: d3d02b5b274410849ba3e6c360e2f005
  - path: Assets/VRLabs/Toony Standard Rebuild Modules/TSR Dissolve
    guid: 0b656aae5208ddf43afc09439c9690dd